trigger:


- master
pool: 
  vmImage: 'ubuntu-latest'
stages:
  - stage: Build
    jobs:
      - job: 'BuildJob'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              goals: 'clean package'

  - stage: Deploy
    jobs:
      - job: 'DeployJob'
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Free Trial(c627ab4c-5b33-4879-9184-05705de1d7b8)'
              appType: 'webAppLinux'
              WebAppName: 'Webapps'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
              RuntimeStack: 'TOMCAT|8.5-jre8'