---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gol
  name: gol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gol
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gol
    spec:
      containers:
      - image: 107636056/newgol
        name: newgol
        resources: {}
status: {}
